language: ruby
cache: bundler
rvm:
  - 2.1.5
  - 2.3.0
services:
  - redis-server
before_install:
  - gem update --system "$(ruby --version | cut -d' ' -f2 | cut -d'p' -f1)"
script:
  - bundle exec rake
